-- Generated by the database client.
CREATE OR REPLACE FUNCTION public.getseqhistoriqueactif() RETURNS bigint
    LANGUAGE plpgsql
    AS $$

BEGIN

    RETURN nextval('seqHistoriqueActif');

END;

$$;
CREATE TABLE historiqueactif(
    id varchar(250) NOT NULL,
    idutilisateur varchar(250),
    estactif integer,
    daty timestamp without time zone,
    PRIMARY KEY(id)
);
alter table historiqueactif add column description varchar(250);

CREATE or replace VIEW public.historiqueactiflib AS
 SELECT id,
    idutilisateur,
    estactif,
    daty,
        CASE
            WHEN (estactif = 0) THEN 'Inactif'::text
            WHEN (estactif = 1) THEN 'Actif'::text
            ELSE 'Inconnu'::text
        END AS estactiflib,
    description
   FROM public.historiqueactif ha;
